#Office STIG hardening
#version 05

#TODO: NEED TO CROSS CHECK ALL HKU KEYS WITH EVERY NTUSER.DAT, THEN ADD:
# reg load HKU\missinguser c:\users\missinguser\ntuser.dat
#Commenting out the HKLM items as these will be handled by Puppet directly

#New-PSDrive -Name HKLM -PSProvider Registry -Root Registry::HKEY_LOCAL_MACHINE
New-PSDrive -Name HKU -PSProvider Registry -Root Registry::HKEY_USERS
$Sids = (Get-ChildItem HKU: | where { $_.Name -notlike "*Classes*" }).PSChildName

$SetArrayU=@()
#$SetArrayM=@()

#HKU
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\mailsettings,PlainWrapLen,REG_DWORD,132"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\access\security,NoTBPromptUnsignedAddin,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security,NoTBPromptUnsignedAddin,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\powerpoint\security,NoTBPromptUnsignedAddin,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,excel12betafilesfromconverters,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\powerpoint\security\fileblock,powerpoint12betafilesfromconverters,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\trusted locations,AllLocationsDisabled,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\trusted locations,AllLocationsDisabled,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\powerpoint\security\trusted locations,AllLocationsDisabled,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security,WordBypassEncryptedMacroScan,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security,ExcelBypassEncryptedMacroScan,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\powerpoint\security,PowerPointBypassEncryptedMacroScan,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\trusted locations,AllowNetworkLocations,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\trusted locations,AllowNetworkLocations,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security\trusted locations,AllowNetworkLocations,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\options,DefaultFormat,REG_DWORD,51"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\options,DefaultFormat,REG_DWORD,27"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security,AccessVBOM,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security,AccessVBOM,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security,AccessVBOM,REG_DWORD,0"
$SetArrayU += "software\policies\Microsoft\office\15.0\access\security,vbawarnings,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security,VBAWarnings,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security,VBAWarnings,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security,ExtensionHardening,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\options,AutoHyperlink,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\options,DisableAutoRepublish,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\options\binaryoptions,fupdateext_78_1,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\options,DisableAutoRepublishWarning,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\internet,DoNotLoadPictures,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\options,MarkupOpenSave,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security,RunPrograms,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\options\binaryoptions,fGlobalSheet_37_1,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security,DownLoadImages,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\access\security,RequireAddinSig,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security,RequireAddinSig,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\filevalidation,EnableOnLoad,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\filevalidation,EnableOnLoad,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security\filevalidation,EnableOnLoad,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,DBaseFiles,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,DifandSylkFiles,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL2Macros,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL2Worksheets,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL3Macros,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL3Worksheets,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL4Macros,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL4Workbooks,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL4Worksheets,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL95Workbooks,REG_DWORD,5"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,XL9597WorkbooksandTemplates,REG_DWORD,5"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\fileblock,OpenInProtectedView,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,OpenInProtectedView,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security\fileblock,OpenInProtectedView,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\protectedview,DisableInternetFilesInPV,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\protectedview,DisableInternetFilesInPV,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security\protectedview,DisableInternetFilesInPV,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\protectedview,DisableUnsafeLocationsInPV,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\protectedview,DisableUnsafeLocationsInPV,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security\protectedview,DisableUnsafeLocationsInPV,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\filevalidation,OpenInProtectedView,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\filevalidation,DisableEditFromPV,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\filevalidation,OpenInProtectedView,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\filevalidation,DisableEditFromPV,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security\filevalidation,OpenInProtectedView,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security\filevalidation,DisableEditFromPV,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\protectedview,DisableAttachmentsInPV,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\protectedview,DisableAttachmentsInPV,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security\protectedview,DisableAttachmentsInPV,REG_DWORD,0"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\toolbars\access,noextensibilitycustomizationfromdocument,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\toolbars\excel,noextensibilitycustomizationfromdocument,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\toolbars\PowerPoint,noextensibilitycustomizationfromdocument,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\slide libraries,DisableSlideUpdate,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security,webservicefunctionwarnings,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\options,extractdatadisableui,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\internet,OpenDocumentsReadWriteWhileBrowsing,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\internet,RelyOnVML,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\internet,AllowPNG,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\ptwatson,PTWOptIn,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\general,ShownFirstRunOptin,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common,QMEnable,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common,UpdateReliabilityData,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\trustcenter,TrustBar,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\security,DRMEncryptProperty,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\Common\Security,AutomationSecurity,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\security,DisableHyperLinkWarning,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\security,DisablePasswordUI,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\security\trusted locations,Allow User Locations,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\Common\Smart Tag,NeverLoadManifests,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\services\fax,NoFax,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\drm,DisableCreation,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\drm,IncludeHTML,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\drm,RequireConnection,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\signatures,EnableCreationOfWeakXPSignatures,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\signatures,SuppressExtSigningSvcs,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\fixedformat,DisableFixedFormatDocProperties,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\documentinformationpanel,Beaconing,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\portal,LinkPublishingDisabled,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\Common\Blog,DisableBlog,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\security,EncryptDocProps,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\internet,UseOnlineContent,REG_DWORD,0"
$SetArrayU += "software\policies\Microsoft\office\15.0\firstrun,disablemovie,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\firstrun,bootedrtm,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\signin,signinoptions,REG_DWORD,2"
$SetArrayU += "software\policies\Microsoft\office\15.0\gfx,disablescreenshotautohyperlink,REG_DWORD,1"
$SetArrayU += "software\Policies\Microsoft\office\15.0\common\general,SkyDriveSignInOption,REG_DWORD,0"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\broadcast,disabledefaultservice,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\broadcast,disableprogrammaticaccess,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\feedback,includescreenshot,REG_DWORD,0"
$SetArrayU += "software\policies\Microsoft\office\15.0\common,feedback,REG_DWORD,0"
$SetArrayU += "software\policies\Microsoft\office\15.0\wef\trustedcatalogs,requireserververification,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\wef\trustedcatalogs,disableomexcatalogs,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\roaming,roamingsettingsdisabled,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\osm,enableupload,REG_DWORD,0"
$SetArrayU += "software\policies\Microsoft\office\15.0\osm,enablefileobfuscation,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\osm,enablelogging,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\publisher\security,RequireAddinSig,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\publisher\security,NoTBPromptUnsignedAddin,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\publisher\security,VBAWarnings,REG_DWORD,2"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\toolbars\publisher,noextensibilitycustomizationfromdocument,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\publisher,PromptForBadFiles,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\Common\Security,AutomationSecurityPublisher,REG_DWORD,3"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,ReadAsPlain,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,ReadSignedAsPlain,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\pubcal,DisableOfficeOnline,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\pubcal,DisableDav,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\pubcal,PublishCalendarDetailsPolicy,REG_DWORD,16384"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\pubcal,RestrictedAccessOnly,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\pubcal,SingleUploadOnly,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook,DisableAntiSpam,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,JunkMailTrustContacts,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,JunkMailTrustOutgoingRecipients,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\mailsettings,DisableSignatures,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,Message Plain Format Mime,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\general,Check Default Client,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,NonDefaultStoreScript,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\general,MSGFormat,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,SharedFolderScript,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,PublicFolderScript,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,AllowActiveXOneOffForms,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,AddinTrust,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,EnableRememberPwd,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook,DisallowAttachmentCustomization,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,AdminSecurityMode,REG_DWORD,3"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\mail,BlockExtContent,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,ShowLevel1Attach,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,AllowUsersToLowerAttachments,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,DontPromptLevel1AttachSend,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,DontPromptLevel1AttachClose,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,EnableOneOffFormScripts,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,PromptOOMCustomAction,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,PromptOOMSend,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,PromptOOMAddressBookAccess,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,PromptOOMAddressInformationAccess,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,PromptOOMMeetingTaskRequestResponse,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,PromptOOMSaveAs,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,PromptOOMFormulaAccess,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,ExternalSMime,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,MsgFormats,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,FIPSMode,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,ClearSign,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,WarnAboutInvalid,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,RespondToReceiptRequests,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,UseCRLChasing,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,SigStatusNoTrustDecision,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,UnblockSpecificSenders,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,UnblockSafeZone,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,TrustedZone,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,Internet,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,Intranet,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,Level,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,JunkMailEnableLinks,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\rpc,EnableRPCEncryption,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,AuthenticationService,REG_DWORD,9"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\rss,SyncToSysCFL,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\rss\Criteria,Disable,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\rss,EnableFullTextHTML,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\webcal,EnableAttachments,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\webcal,Disable,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\meetings\profile,ServerUI,REG_DWORD,2"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\toolbars\outlook,noextensibilitycustomizationfromdocument,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\rss,EnableAttachments,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,EditorPreference,REG_DWORD,65536 (dec)"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,ForceDefaultProfile,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,MinEncKey,REG_DWORD,168"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,NoCheckOnSessionSecurity,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\security,SupressNameChecks,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail\Message RTF,Format,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\outlook\options\calendar,disableweather,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\outlook\options\autoformat,pgrfafo_25_1,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\publisher\security,RequireAddinSig,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\publisher\security,NoTBPromptUnsignedAddin,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\publisher\security,VBAWarnings,REG_DWORD,2"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\toolbars\publisher,noextensibilitycustomizationfromdocument,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\publisher,PromptForBadFiles,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\Common\Security,AutomationSecurityPublisher,REG_DWORD,3"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security,NoTBPromptUnsignedAddin,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\options,DontUpdateLinks,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\options,WarnRevisions,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security,VBAWarnings,REG_DWORD,2"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\toolbars\word,noextensibilitycustomizationfromdocument,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\research\translation,useonline,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\fileblock,Word2Files,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\fileblock,Word2000Files,REG_DWORD,5"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\fileblock,Word60Files,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\fileblock,Word95Files,REG_DWORD,5"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\fileblock,Word97Files,REG_DWORD,5"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security\fileblock,WordXPFiles,REG_DWORD,5"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\options,custommarkupwarning,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security,blockcontentexecutionfrominternet,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,BlockExtContent,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\rss,Disable,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\outlook\options\mail,Message RTF Format,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\PowerPoint\security,blockcontentexecutionfrominternet,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\common\feedback,enabled,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\options,DefaultFormat,REG_SZ, "
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security,blockcontentexecutionfrominternet,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\Outlook\security,blockcontentexecutionfrominternet,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\common\security,OpenXMLEncryptProperty,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\access\security,NoTBPromptUnsignedAddin,REG_DWORD,1"
$SetArrayU += "software\policies\Microsoft\office\15.0\access\security,vbawarnings,REG_DWORD,2"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\access\settings,Default File Format,REG_DWORD,12"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\access\settings,NoConvertDialog,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\access\security,ModalTrustDecisionOnly,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\access\internet,DoNotUnderlineHyperlinks,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\access\security,RequireAddinSig,REG_DWORD,1"
#HKLM
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_ADDON_MANAGEMENT,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_ZONE_ELEVATION,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_RESTRICT_ACTIVEXINSTALL,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_RESTRICT_FILEDOWNLOAD,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WINDOW_RESTRICTIONS,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_HTTP_USERNAME_PASSWORD_DISABLE,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_SAFE_BINDTOOBJECT,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_UNC_SAVEDFILECHECK,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_VALIDATE_NAVIGATE_URL,msaccess.exe,REG_DWORD,1"
#$SetArrayM += "Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WEBOC_POPUPMANAGEMENT,msaccess.exe,REG_DWORD,1"
#
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\word\security,RequireAddinSig,REG_DWORD,0"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\powerpoint\security,RequireAddinSig,REG_DWORD,1"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\powerpoint\security,VBAWarnings,REG_DWORD,3"
$SetArrayU += "Software\Policies\Microsoft\Office\15.0\excel\security\fileblock,HtmlandXmlssFiles,REG_DWORD,0"


#if (!(Test-Path "HKLM:\Software\Microsoft\Internet Explorer\Main\FeatureControl")) {
#  New-Item -Path "HKLM:\Software\Microsoft\Internet Explorer\Main\FeatureControl" -Name security -Force
#}

#foreach($setting in $SetArrayM) {
#  $regset = "HKLM\" + $setting.split(",")[0]
#  $regotherthing = $setting.split(",")[1]
#  $regtype = $setting.split(",")[2]
#  $regval = $setting.split(",")[3]

#  cmd /c reg add `"$regset`" /t $regtype /v $regotherthing /d `"$regval`" /f
#  echo "cmd /c reg add $regset /t $regtype /v $regotherthing /d $regval /f"
#}

foreach ($sid in $Sids) {
  if (!(Test-Path "HKU:\$sid\Software\Policies\Microsoft\Office\15.0\common\security")) {
    New-Item -Path "HKU:\$sid\Software\Policies\Microsoft\Office\15.0\common" -Name security -Force
  }

  New-ItemProperty -Path "HKU:\$sid\Software\Policies\Microsoft\Office\15.0\common\security" -Name DefaultEncryption12 -PropertyType "String" -Value "Microsoft Enhanced RSA and AES Cryptographic Provider, AES 256,256" -Force | Out-Null
  New-ItemProperty -Path "HKU:\$sid\Software\Policies\Microsoft\Office\15.0\common\security" -Name OpenXMLEncryption -PropertyType "String" -Value "Microsoft Enhanced RSA and AES Cryptographic Provider, AES 256,256" -Force | Out-Null

  foreach($setting in $SetArrayU) {
    $regset = "HKU\" + $sid + "\" + $setting.split(",")[0]
    $regotherthing = $setting.split(",")[1]
    $regtype = $setting.split(",")[2]
    $regval = $setting.split(",")[3]

    cmd /c reg add `"$regset`" /t $regtype /v $regotherthing /d `"$regval`" /f
    echo "cmd /c reg add $regset /t $regtype /v $regotherthing /d $regval /f"

    Remove-ItemProperty -Path "HKU:\$sid\Software\Policies\Microsoft\Office\15.0\outlook\security\OutlookSecureTempFolder" -Name EnableAttachments -EA SilentlyContinue
    Remove-ItemProperty -Path "HKU:\$sid\Software\Policies\Microsoft\Office\15.0\outlook\security" -Name FileExtensionRemoveLevel1 -EA SilentlyContinue
    Remove-ItemProperty -Path "HKU:\$sid\Software\Policies\Microsoft\Office\15.0\outlook\security" -Name FileExtensionRemoveLevel2 -EA SilentlyContinue
  }
}

$usercount=(gci -path registry::hkey_users).count
New-ItemProperty -path HKLM:\software\dcgs\patches -name hkuctoffice -value $usercount -propertytype dword -force
